- hosts: all
  user: pi
  sudo: true
  sudo_user: root
  vars_files:
    - vars/private.yml

  tasks:
    - name: Install Packages
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=86400
      with_items:
        - zsh
        - openssh-client

    - name: Create my personal account
      user: name=mahata

    - name: Make sure ~mahata/.ssh exists
      file: dest=/home/mahata/.ssh state=directory owner=mahata group=mahata mode=0700

    - name: Set SSH private key
      copy: content="{{ ssh_private_key }}" dest=/home/mahata/.ssh/id_rsa owner=mahata group=mahata mode=0600

    - name: Set SSH public key
      copy: content="{{ ssh_public_key }}" dest=/home/mahata/.ssh/authorized_keys owner=mahata group=mahata mode=0600

    - name: Copy ~/.ssh/config
      copy: src=files/sshconfig dest=/home/mahata/.ssh/config owner=mahata group=mahata mode=0600

    - name: Make sure /root/.ssh exists
      file: dest=/root/.ssh state=directory owner=root group=root mode=0700

    - name: Set SSH private key (root)
      copy: content="{{ ssh_private_key }}" dest=/root/.ssh/id_rsa owner=root group=root mode=0600

    - name: Set SSH public key (root)
      copy: content="{{ ssh_public_key }}" dest=/root/.ssh/authorized_keys owner=root group=root mode=0600

    - name: Copy /root/.ssh/config
      copy: src=files/sshconfig dest=/root/.ssh/config owner=root group=root mode=0600

    - name: Copy /etc/hosts for mutual connectivity
      copy: src=files/hosts dest=/etc/hosts force=yes

    - name: Set timezone to Tokyo
      copy: content="Asia/Tokyo" dest=/etc/timezone owner=root group=root mode=0644 backup=yes
      notify:
        - update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
