- hosts: all
  user: pi
  sudo: true
  sudo_user: root
  vars_files:
    - vars/private.yml

  tasks:
    - name: Install Packages
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - zsh

    - name: Create my personal account
      user: name=mahata
